name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install Dependencies
        run: npm install

      - name: Rebuild Fresh Android Folder
        run: |
          rm -rf android
          npx cap add android
          npx cap sync android

      - name: Generate App Icons & Splash Screen
        run: |
          npm i -D @capacitor/assets
          npx @capacitor/assets generate --android

      - name: Inject Permanent Keystore
        run: |
          mkdir -p ~/.android
          cp my-app-key.keystore ~/.android/debug.keystore

      - name: Add Firebase Config
        run: |
          mkdir -p android/app
          echo '{
            "project_info": {
              "project_number": "998280256788",
              "project_id": "aboroqya-4a460",
              "storage_bucket": "aboroqya-4a460.firebasestorage.app"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:998280256788:android:105cfdff77e5dd19d3b601",
                  "android_client_info": {
                    "package_name": "Com.ejramgamal.json"
                  }
                },
                "oauth_client": [],
                "api_key": [
                  {
                    "current_key": "AIzaSyCcKXCMRlVWV7jo53v5EBXYErcq9-d4slQ"
                  }
                ]
              }
            ],
            "configuration_version": "1"
          }' > android/app/google-services.json

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DebtTracker-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
